server:
  port: 80
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: cloud-stream
  rabbitmq:
    addresses: amqp://192.168.1.216:5672
    username: alan
    password: alan