server:
  port: 81
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: cloud-stream
          group: group1
          consumer:
            durableSubscription: true
  rabbitmq:
    addresses: amqp://192.168.1.216:5672
    username: alan
    password: alan